# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1629, 897)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_open_camera = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_camera.setGeometry(QtCore.QRect(40, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_open_camera.setFont(font)
        self.button_open_camera.setObjectName("button_open_camera")
        self.button_Face_Detection = QtWidgets.QPushButton(self.centralwidget)
        self.button_Face_Detection.setGeometry(QtCore.QRect(40, 440, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_Face_Detection.setFont(font)
        self.button_Face_Detection.setObjectName("button_Face_Detection")
        self.button_Face_Recognition = QtWidgets.QPushButton(self.centralwidget)
        self.button_Face_Recognition.setGeometry(QtCore.QRect(40, 540, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_Face_Recognition.setFont(font)
        self.button_Face_Recognition.setObjectName("button_Face_Recognition")
        self.button_Close = QtWidgets.QPushButton(self.centralwidget)
        self.button_Close.setGeometry(QtCore.QRect(590, 730, 181, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_Close.setFont(font)
        self.button_Close.setObjectName("button_Close")
        self.label_show_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_show_camera.setGeometry(QtCore.QRect(380, 100, 640, 480))
        self.label_show_camera.setObjectName("label_show_camera")
        self.label_ShowPic = QtWidgets.QLabel(self.centralwidget)
        self.label_ShowPic.setGeometry(QtCore.QRect(1070, 120, 430, 430))
        self.label_ShowPic.setObjectName("label_ShowPic")
        self.button_Speech_Recognition = QtWidgets.QPushButton(self.centralwidget)
        self.button_Speech_Recognition.setGeometry(QtCore.QRect(40, 640, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_Speech_Recognition.setFont(font)
        self.button_Speech_Recognition.setObjectName("button_Speech_Recognition")
        self.button_Chat = QtWidgets.QPushButton(self.centralwidget)
        self.button_Chat.setGeometry(QtCore.QRect(40, 740, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_Chat.setFont(font)
        self.button_Chat.setObjectName("button_Chat")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1310, 580, 296, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(430, 10, 501, 71))
        font = QtGui.QFont()
        font.setFamily("叶根友毛笔行书2.0版")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton.setFont(font)
        self.toolButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton.setObjectName("toolButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(500, 810, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.btn_photo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_photo.setGeometry(QtCore.QRect(40, 130, 180, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_photo.setFont(font)
        self.btn_photo.setObjectName("btn_photo")
        self.btn_input_name = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input_name.setGeometry(QtCore.QRect(40, 230, 180, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_input_name.setFont(font)
        self.btn_input_name.setObjectName("btn_input_name")
        self.btn_input_information = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input_information.setGeometry(QtCore.QRect(40, 330, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_input_information.setFont(font)
        self.btn_input_information.setObjectName("btn_input_information")
        self.textBrowser_Show_Infor = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Show_Infor.setGeometry(QtCore.QRect(850, 580, 421, 271))
        self.textBrowser_Show_Infor.setObjectName("textBrowser_Show_Infor")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 620, 251, 181))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1629, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionpaste = QtWidgets.QAction(MainWindow)
        self.actionpaste.setObjectName("actionpaste")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionClose)
        self.menu_2.addAction(self.actionCopy)
        self.menu_2.addAction(self.actionCut)
        self.menu_2.addAction(self.actionpaste)
        self.menu_2.addAction(self.actionRedo)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_open_camera.setText(_translate("MainWindow", "请打开摄像头"))
        self.button_Face_Detection.setText(_translate("MainWindow", "情 绪 分 析"))
        self.button_Face_Recognition.setText(_translate("MainWindow", "进行人脸识别"))
        self.button_Close.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\">您真的想要退出系统吗？</span></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.button_Close.setText(_translate("MainWindow", "退 出 系 统"))
        self.label_show_camera.setText(_translate("MainWindow", "label_show_camera"))
        self.label_ShowPic.setText(_translate("MainWindow", "ShowPic"))
        self.button_Speech_Recognition.setText(_translate("MainWindow", "进行语言识别"))
        self.button_Chat.setText(_translate("MainWindow", "开启聊天模式"))
        self.toolButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">这是人脸识别的主界面</span></p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "人脸识别系统"))
        self.btn_photo.setText(_translate("MainWindow", "拍        照"))
        self.btn_input_name.setText(_translate("MainWindow", "输 入 姓 名"))
        self.btn_input_information.setText(_translate("MainWindow", "录 入 信 息"))
        self.textBrowser_Show_Infor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">目标人物信息展示</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:14pt; font-weight:600; font-style:italic; color:#ffffff;\">@Author：Thrones<br />Q     Q：1690069811<br />TelephoneNumber：18885672964<br />Email：yang18885672964@gmail.com<br />GitHub:<br />https://github.com/FightingThrones?tab=repositories</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionCopy.setText(_translate("MainWindow", "复制"))
        self.actionCut.setText(_translate("MainWindow", "剪切"))
        self.actionpaste.setText(_translate("MainWindow", "粘贴"))
        self.actionRedo.setText(_translate("MainWindow", "撤销"))


